new features and bugfixes
- support fot 'targets' (iSCSI)
- adapt volume and pool status and detect it correctly ('Ready')
- move common snmp-get and processing into function
  get_snmp_and_process
- prepare options for negative filtering '-F'

diff --git a/storage/snmp_qnapstorage b/storage/snmp_qnapstorage
--- a/storage/snmp_qnapstorage
+++ b/storage/snmp_qnapstorage
@@ -4,7 +4,17 @@
 # QNAP devices using SNMP. It takes into account the QNAP's status of
 # volumes and pools and merges it with the CLI thesholds
 #
-# Version: 1.0 Author: msander
+# Author: msander
+#
+# Version: 1.2 2023-02-14
+#   Bugfixes
+#
+# Version: 1.1 2023-02-13
+#   Added support for network targets (e.g. iSCSI)
+#   
+# Version: 1.0  2023-02-09
+#   First productive version
+#
 #
 
 # Define Vars
@@ -19,7 +29,7 @@ glob_rcode=0
 #
 
 OPTERR=1
-while getopts "H:C:u:x:X:a:A:l:w:c:m:f:t:Bhd" OPTION ; do
+while getopts "H:C:u:x:X:a:A:l:w:c:m:f:F:t:Bhd" OPTION ; do
     case "${OPTION}" in
         H) hostname=${OPTARG}       ;;
         C) community="-c ${OPTARG}" ;;
@@ -29,14 +39,15 @@ while getopts "H:C:u:x:X:a:A:l:w:c:m:f:t:Bhd" OPTION ; do
         x) privproto="-x ${OPTARG}" ;;
         X) privpass="-X ${OPTARG}"  ;;
         l) seclevel="-l ${OPTARG}"  ;;
-        w) warn=${OPTARG}       ;;
-        c) crit=${OPTARG}       ;;
-        m) mode=${OPTARG}       ;;
-        f) filter=${OPTARG}     ;;
-        t) tout=${OPTARG}       ;;
-        B) nobulk=1         ;;
-        h) helpme=1         ;;
-        d) debug=1      ;;
+        w) warn=${OPTARG}           ;;
+        c) crit=${OPTARG}           ;;
+        m) mode=${OPTARG}           ;;
+        f) filter=${OPTARG}         ;;
+        F) neg_filter=${OPTARG}     ;;
+        t) tout=${OPTARG}           ;;
+        B) nobulk=1                 ;;
+        h) helpme=1                 ;;
+        d) debug=1                  ;;
     esac
 done
 
@@ -103,6 +114,7 @@ function state_string() {
 function translate_pool_status() {
     local numcode=$1
     local version=$2
+    local rstat
     version=QuTS
 
     case $version in 
@@ -121,7 +133,7 @@ function translate_pool_status() {
                 '-1')
                     rstat='WARNING' ;;
                 0)
-                    rstat='READY'   ;;
+                    rstat='Ready'   ;;
                 1)
                     rstat='ENABLE_QTIER'    ;;
                 2)
@@ -140,7 +152,7 @@ function translate_pool_status() {
                 '-1')
                     rstat='WARNING' ;;
                 0)
-                    rstat='READY'   ;;
+                    rstat='Ready'   ;;
                 1)
                     rstat='RESILVERING' ;;
                 2)
@@ -176,12 +188,27 @@ function translate_pool_status() {
     echo $rstat
 }
 
+function translate_target_status() {
+    local numcode=$1
+
+    case $numcode in
+        '-1')
+            rstat='offline'     ;;
+        0)
+            rstat='ready'        ;;
+        1)
+            rstat='connected'    ;;
+    esac
+    echo $rstat
+}
+
 function mode_string() {
     local mode=$1
     local string
     case $mode in 
         pool) string='Pools' ;;
         volume) string='Volumes' ;;
+    target) string='Targets' ;;
     esac
     echo $string
 }
@@ -241,7 +268,11 @@ function storage_byfilter() {
         vol_status=${snmpData[${baseOID}.${id[status]}.$element]}
 
     if [ $mode == 'pool' ] ; then
+    # Pools have a numeric status
         vol_status=$( translate_pool_status $vol_status )
+    else
+    # Volumes have a string status. Remove quotes.
+        vol_status=$( echo $vol_status | tr -d '"' )
     fi
         
     # Calc local return code / state text string
@@ -252,7 +283,7 @@ function storage_byfilter() {
         glob_rcode=$( calc_globalstate ${percent} $warn $crit )
     fi
 
-    if [ $vol_status != 'READY' ] ;then 
+    if [ $vol_status != 'Ready' ] ;then 
         # Update global return code
         glob_rcode=$( set_globalstate 1 )
     fi
@@ -308,6 +339,113 @@ function raid_byfilter() {
     done
 }
 
+function target_byfilter() {
+    # Print Out Data for Elements, filtered by Name
+    # By default, select all elements
+
+    local filter=$1
+
+    for eName in ${!nameMap[@]}
+    do
+        if [[  "$eName" =~ $filter ]]
+        then
+            outElements+=(${nameMap[$eName]})
+        fi
+    done
+
+    if [ ${#outElements[@]} -ne 0 ] ; then
+        outmsg+="$( mode_string $mode ): "
+    else
+        outmsg+="No $( mode_string $mode ) found"
+    fi
+
+
+    local loop_rcode=0
+    local loop_state
+    for element in  ${outElements[@]}
+    do
+        local name=${snmpData[${baseOID}.${id[name]}.$element]}
+        local iqn=${snmpData[${baseOID}.${id[iqn]}.$element]}
+        local ip=${snmpData[${baseOID}.${id[ip]}.$element]}
+        local target_status=${snmpData[${baseOID}.${id[status]}.$element]}
+    local target_status_string=$( translate_target_status $target_status )
+
+    # Map QNAP target status to return code
+    case $target_status in 
+        -1) loop_rcode=2;;
+        0)  loop_rcode=1;;
+        1)  loop_rcode=0;;
+    esac
+
+        loop_state=$( state_string $loop_rcode )
+        glob_rcode=$( set_globalstate $loop_rcode ) 
+
+        # text output
+        outmsg+="$name, Status: \"$target_status_string\"; "
+        details+="$loop_state Target $name\n"
+        details+="  IQN:    $iqn\n"
+        details+="  IP:     $ip\n"
+        details+="  Status: \"$target_status_string\"\n\n"
+    done
+}
+
+function get_snmp_and_process {
+    #
+    # Compose snmp command
+    #
+    if [ "$nobulk" ]; then walk=snmpwalk;  else walk=snmpbulkwalk; fi
+    if [ -n "$authuser" ]; then snmpv=3; else snmpv=2c; fi
+
+    snmpcmd="$walk -Onq -v $snmpv -t $tout -r 3 \
+        $community $authuser $privproto $privpass $seclevel $authproto $authpass \
+        $hostname  $baseOID"
+
+    if [ -n "$debug" ] ; then echo "debug: $snmpcmd" ; fi
+
+
+    # First of all, get the SNMP-Data
+    snmpResponse=$($snmpcmd 2>&1)
+    snmpexit=$?
+
+    if [ $snmpexit -ne 0 ] ; then
+        echo "(UNKNOWN): Problem fetching SNMP data."
+        echo 
+        echo "SNMP Output was: $snmpResponse"
+        exit 3
+    fi
+
+    while read oid value unit
+    do 
+        snmpData[$oid]="$value"
+    done <<< "$snmpResponse"
+
+    #### building indexes
+    #
+
+    # build element index
+    for key in ${!snmpData[@]} ; do
+        if [[ $key == "$baseOID.${id[index]}"* ]] ; then
+        elementIndex+=( ${snmpData[$key]} )
+        fi
+    done
+
+    # build name map
+    for element in  ${elementIndex[@]}
+    do
+        nameMap[${snmpData[${baseOID}.${id[name]}.$element]}]=${snmpData[${baseOID}.${id[index]}.$element]}
+    done
+
+    # build element map
+    for eName in ${!nameMap[@]}
+    do
+        element=${nameMap[$eName]}
+    done
+
+    #
+    #
+    #### / building indexes
+}
+
 #
 # MAIN
 #
@@ -319,31 +457,6 @@ mode=${mode:=volume}
 filter=${filter:=.}
 tout=${tout:=20}
 
-case $mode in
-    raid)
-        baseOID='.1.3.6.1.4.1.55062.1.10.5.1'
-        id[index]=1
-        id[name]=3
-        id[size]=5
-        id[status]=4    ;;
-    pool)
-        baseOID='.1.3.6.1.4.1.55062.1.10.7.1'
-        id[index]=1
-        id[name]=2
-        id[size]=3
-        id[free]=4
-        id[status]=5    ;;
-    volume)
-        baseOID='.1.3.6.1.4.1.55062.1.10.9.1'
-        id[index]=1
-        id[name]=8
-        id[size]=3
-        id[free]=4
-        id[status]=5    ;;
-    *)
-        echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
-esac
-
 # 
 # precission calculator 'bc' compat. check
 #
@@ -353,73 +466,58 @@ elif [ -x /usr/bin/bc ] ; then
     bc=/usr/bin/bc
 fi
 
-#
-# Compose snmp command
-#
-if [ "$nobulk" ]; then walk=snmpwalk;  else walk=snmpbulkwalk; fi
-if [ -n "$authuser" ]; then snmpv=3; else snmpv=2c; fi
-
-snmpcmd="$walk -Onq -v $snmpv -t $tout -r 3 \
-    $community $authuser $privproto $privpass $seclevel $authproto $authpass \
-    $hostname  $baseOID"
-
-if [ -n "$debug" ] ; then echo "debug: $snmpcmd" ; fi
-
-
-# First of all, get the SNMP-Data
-snmpResponse=$($snmpcmd 2>&1)
-snmpexit=$?
-
-if [ $snmpexit -ne 0 ] ; then
-    echo "(UNKNOWN): Problem fetching SNMP data."
-    echo 
-    echo "SNMP Output was: $snmpResponse"
-    exit 3
-fi
-
-while read oid value unit
-do 
-    snmpData[$oid]="$value"
-done <<< "$snmpResponse"
-
-#### building indexes
-#
-
-# build element index
-for key in ${!snmpData[@]} ; do
-    if [[ $key == "$baseOID.${id[index]}"* ]] ; then
-        elementIndex+=( ${snmpData[$key]} )
-    fi
-done
-
-# build name map
-for element in  ${elementIndex[@]}
-do
-    nameMap[${snmpData[${baseOID}.${id[name]}.$element]}]=${snmpData[${baseOID}.${id[index]}.$element]}
-done
-
-# build element map
-for eName in ${!nameMap[@]}
-do
-    element=${nameMap[$eName]}
-done
-
-#
-#
-#### / building indexes
-
-
 case $mode in
     pool)
-        storage_byfilter $filter;;
+        baseOID='.1.3.6.1.4.1.55062.1.10.7.1'
+        id[index]=1
+        id[name]=2
+        id[size]=3
+        id[free]=4
+        id[status]=5
+        get_snmp_and_process 
+        storage_byfilter $filter
+    ;;
+    
     volume)
-        storage_byfilter $filter;;
+        baseOID='.1.3.6.1.4.1.55062.1.10.9.1'
+        id[index]=1
+        id[name]=8
+        id[size]=3
+        id[free]=4
+        id[status]=5
+        get_snmp_and_process 
+        storage_byfilter $filter
+    ;;
+    
     raid)
-        raid_byfilter $filter;;
+        baseOID='.1.3.6.1.4.1.55062.1.10.5.1'
+        id[index]=1
+        id[name]=3
+        id[size]=5
+        id[status]=4
+        get_snmp_and_process 
+        raid_byfilter $filter
+    ;;
+
+    target)
+        baseOID='.1.3.6.1.4.1.55062.1.10.22.1'
+        id[index]=1
+        id[name]=3
+        id[iqn]=4
+        id[ip]=5
+        id[status]=6
+        get_snmp_and_process 
+        target_byfilter $filter
+    ;;
+
+    *)
+        echo "(UNKNOWN): mode '-m $mode' not known" ; exit 3 ;;
 esac
 
 
-
+#
+# Tell monitoring system what we found out
+#
 echo -en "$( state_string $glob_rcode ) $outmsg"
 if [ -n "$details" ] ; then echo -en "\n\n$details" ; fi
 if [ -n "$perfdata" ] ; then echo -en "|$perfdata" ; fi
